### Passo 1 - Importar Arquivos e Bibliotecas

In [1]:
import pandas as pd 
import openpyxl

In [2]:
emails = pd.read_excel(r"Bases de Dados\Emails.xlsx")
lojas = pd.read_csv(r"Bases de Dados\Lojas.csv", encoding = "latin1", sep = ";")
vendas = pd.read_excel(r"Bases de Dados\Vendas.xlsx")

display(emails)
display(lojas)
display(vendas)

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,pythonimpressionador+helena@gmail.com
1,Shopping Midway Mall,Alice,pythonimpressionador+alice@gmail.com
2,Norte Shopping,Laura,pythonimpressionador+laura@gmail.com
3,Shopping Iguatemi Fortaleza,Manuela,pythonimpressionador+manuela@gmail.com
4,Shopping União de Osasco,Valentina,pythonimpressionador+valentina@gmail.com
5,Shopping Center Interlagos,Sophia,pythonimpressionador+sophia@gmail.com
6,Rio Mar Recife,Isabella,pythonimpressionador+isabella@gmail.com
7,Salvador Shopping,Heloisa,pythonimpressionador+heloisa@gmail.com
8,Rio Mar Shopping Fortaleza,Luiza,pythonimpressionador+luiza@gmail.com
9,Shopping Center Leste Aricanduva,Julia,pythonimpressionador+julia@gmail.com
10,Ribeirão Shopping,Lorena,pythonimpressionador+lorena@gmail.com
11,Shopping Morumbi,Livia,pythonimpressionador+livia@gmail.com
12,Parque Dom Pedro Shopping,Maria Luiza,pythonimpressionador+maria_luiza@gmail.com
13,Bourbon Shopping SP,Cecilia,pythonimpressionador+cecilia@gmail.com
14,Palladium Shopping Curitiba,Eloa,pythonimpressionador+eloa@gmail.com
15,Passei das Águas Shopping,Miguel,pythonimpressionador+miguel@gmail.com
16,Center Shopping Uberlândia,Arthur,pythonimpressionador+arthur@gmail.com
17,Shopping Recife,Heitor,pythonimpressionador+heitor@gmail.com
18,Shopping Vila Velha,Bernardo,pythonimpressionador+bernardo@gmail.com
19,Shopping SP Market,Davi,pythonimpressionador+davi@gmail.com
20,Shopping Eldorado,Theo,pythonimpressionador+theo@gmail.com
21,Shopping Ibirapuera,Lorenzo,pythonimpressionador+lorenzo@gmail.com
22,Novo Shopping Ribeirão Preto,Gabriel,pythonimpressionador+gabriel@gmail.com
23,Iguatemi Campinas,Pedro,pythonimpressionador+pedro@gmail.com
24,Shopping Barra,Benjamin,pythonimpressionador+benjamin@gmail.com
25,Diretoria,Diretoria,pythonimpressionador+diretoria@gmail.com

    ID Loja                              Loja
0         1                Iguatemi Esplanada
1         2              Shopping Midway Mall
2         3                    Norte Shopping
3         4       Shopping Iguatemi Fortaleza
4         5          Shopping União de Osasco
5         6        Shopping Center Interlagos
6         7                    Rio Mar Recife
7         8                 Salvador Shopping
8         9        Rio Mar Shopping Fortaleza
9        10  Shopping Center Leste Aricanduva
10       11                 Ribeirão Shopping
11       12                  Shopping Morumbi
12       13         Parque Dom Pedro Shopping
13       14               Bourbon Shopping SP
14       15       Palladium Shopping Curitiba
15       16         Passei das Águas Shopping
16       17        Center Shopping Uberlândia
17       18                   Shopping Recife
18       19               Shopping Vila Velha
19       20                Shopping SP Market
20       21                 Shopping Eldorado
21       22               Shopping Ibirapuera
22       23      Novo Shopping Ribeirão Preto
23       24                 Iguatemi Campinas
24       25                    Shopping Barra

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71
...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204
100995,69996,2019-12-26,17,Mochila,4,270,1080
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108
100998,69997,2019-12-26,11,Short Linho,2,133,266

### Passo 2 - Definir Criar uma Tabela para cada Loja e Definir o dia do Indicador

In [3]:
vendas = vendas.merge(lojas, on = "ID Loja")

display(vendas)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
3,2,2019-01-02,3,Relógio,3,200,600,Norte Shopping
4,2,2019-01-02,3,Chinelo Liso,1,71,71,Norte Shopping
...,...,...,...,...,...,...,...,...
100994,69996,2019-12-26,17,Short Listrado,2,102,204,Center Shopping Uberlândia
100995,69996,2019-12-26,17,Mochila,4,270,1080,Center Shopping Uberlândia
100996,69996,2019-12-26,17,Pulseira Estampa,1,87,87,Center Shopping Uberlândia
100997,69997,2019-12-26,11,Camisa Listrado,1,108,108,Ribeirão Shopping
100998,69997,2019-12-26,11,Short Linho,2,133,266,Ribeirão Shopping

In [4]:
dict_lojas = {}

for loja in lojas["Loja"]:
    dict_lojas[loja] = vendas.loc[vendas["Loja"] == loja, :]

display(dict_lojas["Rio Mar Recife"])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
62,46,2019-01-02,7,Camisa,1,100,100,Rio Mar Recife
63,46,2019-01-02,7,Calça Liso,2,190,380,Rio Mar Recife
64,46,2019-01-02,7,Cinto,1,200,200,Rio Mar Recife
113,87,2019-01-02,7,Camisa Estampa,1,113,113,Rio Mar Recife
142,109,2019-01-02,7,Camisa Gola V Listrado,3,116,348,Rio Mar Recife
...,...,...,...,...,...,...,...,...
100858,69905,2019-12-25,7,Mochila Listrado,2,275,550,Rio Mar Recife
100859,69905,2019-12-25,7,Camisa Xadrez,3,105,315,Rio Mar Recife
100860,69905,2019-12-25,7,Tênis Liso,3,266,798,Rio Mar Recife
100929,69954,2019-12-25,7,Chinelo,3,60,180,Rio Mar Recife
100930,69954,2019-12-25,7,Casaco Listrado,3,269,807,Rio Mar Recife

In [5]:
dia_indicador = vendas["Data"].max()
print(dia_indicador)

2019-12-26 00:00:00

### Passo 3 - Salvar a planilha na pasta de backup

In [6]:
import pathlib

caminho_backup = pathlib.Path(r"Backup Arquivos Lojas")

arquivos_pasta_backup = caminho_backup.iterdir()
lista_nomes_backup = [arquivo.name for arquivo in arquivos_pasta_backup]

for loja in dict_lojas:
    if loja not in lista_nomes_backup:
        nova_pasta = caminho_backup / loja
        nova_pasta.mkdir()

    nome_arquivo = f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"
    local_arquivo = caminho_backup / loja / nome_arquivo

    dict_lojas[loja].to_excel(local_arquivo)

### Passo 4 - Calcular o indicador para 1 loja

In [7]:
meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

In [8]:
for loja in dict_lojas:


    vendas_loja = dict_lojas[loja]
    vendas_loja_dia = vendas_loja.loc[vendas_loja["Data"] == dia_indicador, :]

    #Faturamento
    faturamento_ano = vendas_loja["Valor Final"].sum()
    #print(faturamento_ano)
    faturamento_dia = vendas_loja_dia["Valor Final"].sum()
    #print(faturamento_dia)

    #Diversidade Produtos
    qtde_produtos_ano = len(vendas_loja["Produto"].unique())
    #print(qtde_produtos_ano)
    qtde_produtos_dia = len(vendas_loja_dia["Produto"].unique())
    #print(qtde_produtos_dia)



    # Ticket Médio
    valor_venda = vendas_loja.groupby("Código Venda")["Valor Final"].sum()
    ticket_medio_ano = valor_venda.mean()
    #print(ticket_medio_ano)

    valor_venda_dia = vendas_loja_dia.groupby("Código Venda")["Valor Final"].sum()
    ticket_medio_dia = valor_venda_dia.mean()
    #print(ticket_medio_dia)


    import smtplib # lib que faz o processo de envio do email
    from email.message import EmailMessage # lib para criar a mensagem do email
    from dotenv import load_dotenv # usada para importar as variáveis do .env
    import os # usada paara acessar o sistema

    load_dotenv() # carega o conteúdo do .env
    SENHA_APP = os.getenv("SENHA_APP")

    EMAIL_REMETENTE = "ghost60209@gmail.com"


    nome = emails.loc[emails["Loja"] == loja, "Gerente"].values[0]

    msg = EmailMessage()
    msg["From"] = EMAIL_REMETENTE
    msg["Cc"] = "ghost60209+copia@gmail.com"
    msg["To"] = emails.loc[emails["Loja"] == loja, "E-mail"].values[0]
    msg["Subject"] = f"OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}"

    msg.set_content("Olá")

    if faturamento_dia >= meta_faturamento_dia:
        cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if qtde_produtos_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if qtde_produtos_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if ticket_medio_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if ticket_medio_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'



    msg.add_alternative(f"""
    <!DOCTYPE html>
    <html>
        <body>
            <p>Bom dia, {nome}</p>
            <p>O resultado de ontem <strong>({dia_indicador.day}/{dia_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

            <table>
                <tr>
                    <th>Indicador</th>
                    <th>Valor Dia</th>
                    <th>Meta Dia</th>
                    <th>Cenário Dia</th>
                </tr>
                <tr>
                    <td>Faturamento</td>
                    <td style = "text-align: center">R$ {faturamento_dia:.2f}</td>
                    <td style = "text-align: center">R$ {meta_faturamento_dia:.2f}</td>
                    <td style = "text-align: center"><font color = "{cor_fat_dia}">◙</font></td>
                </tr>
                <tr>
                    <td>Diversidade de Produtos</td>
                    <td style = "text-align: center">{qtde_produtos_dia}</td>
                    <td style = "text-align: center">{meta_qtdeprodutos_dia}</td>
                    <td style = "text-align: center"><font color = "{cor_qtde_dia}">◙</font></td>
                </tr>
                <tr>
                    <td>Ticket Médio</td>
                    <td style = "text-align: center">R$ {ticket_medio_dia:.2f}</td>
                    <td style = "text-align: center">R$ {meta_ticketmedio_dia:.2f}</td>
                    <td style = "text-align: center"><font color = "{cor_ticket_dia}">◙</font></td>
                </tr>
                <p></p>
                <br>
                <tr>
                    <th>Indicador</th>
                    <th>Valor Ano</th>
                    <th>Meta Ano</th>
                    <th>Cenário Ano</th>
                </tr>
                <tr>
                    <td>Faturamento</td>
                    <td style = "text-align: center">R$ {faturamento_ano:.2f}</td>
                    <td style = "text-align: center">R$ {meta_faturamento_ano:.2f}</td>
                    <td style = "text-align: center"><font color = "{cor_fat_ano}">◙</font></td>
                </tr>
                <tr>
                    <td>Diversidade de Produtos</td>
                    <td style = "text-align: center">{qtde_produtos_ano}</td>
                    <td style = "text-align: center">{meta_qtdeprodutos_ano}</td>
                    <td style = "text-align: center"><font color = "{cor_qtde_ano}">◙</font></td>
                </tr>
                <tr>
                    <td>Ticket Médio</td>
                    <td style = "text-align: center">R$ {ticket_medio_ano:.2f}</td>
                    <td style = "text-align: center">R$ {meta_ticketmedio_ano:.2f}</td>
                    <td style = "text-align: center"><font color = "{cor_ticket_ano}">◙</font></td>

            </table>
            <br>
            <p></p>
            <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>
            <p>Qualquer dúvida estou à disposição</p>
            <p>Att., Equipe de Dados.

        </body>
    """, subtype = "html")



    # Anexo

    caminho_arquivo = pathlib.Path.cwd() / caminho_backup / loja / f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"

    with open(caminho_arquivo, "rb") as f: #aqui abre o arquivo e ja o fecha automaticamente, lê ele em modo binário com "rb"
        msg.add_attachment( # aqui irá fazer a função do multipart
            f.read(), # aqui vai o arquivo inteiro, todos os bytes
            maintype = "application", #define a categoria do anexo, aqui como esta "aplication" é para arquivos genáricos como pdf, zip, img, ect...
            subtype = "octet-stream", # aqui trata o arquivo como download
            filename = caminho_arquivo.name #aqui envia so o nome do arquivo e não seu caminho
        )


    # Enviar e-mail

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp: # aqui abre conexão segura
        smtp.login(EMAIL_REMETENTE, SENHA_APP) # loga na minha conta
        smtp.send_message(msg) # manda a msg


    print(f"Email enviado com sucesso!, paras a loja {loja}")

Email enviado com sucesso!, paras a loja Iguatemi Esplanada
Email enviado com sucesso!, paras a loja Shopping Midway Mall
Email enviado com sucesso!, paras a loja Norte Shopping
Email enviado com sucesso!, paras a loja Shopping Iguatemi Fortaleza
Email enviado com sucesso!, paras a loja Shopping União de Osasco
Email enviado com sucesso!, paras a loja Shopping Center Interlagos
Email enviado com sucesso!, paras a loja Rio Mar Recife
Email enviado com sucesso!, paras a loja Salvador Shopping
Email enviado com sucesso!, paras a loja Rio Mar Shopping Fortaleza
Email enviado com sucesso!, paras a loja Shopping Center Leste Aricanduva
Email enviado com sucesso!, paras a loja Ribeirão Shopping
Email enviado com sucesso!, paras a loja Shopping Morumbi
Email enviado com sucesso!, paras a loja Parque Dom Pedro Shopping
Email enviado com sucesso!, paras a loja Bourbon Shopping SP
Email enviado com sucesso!, paras a loja Palladium Shopping Curitiba
Email enviado com sucesso!, paras a loja Passei das Águas Shopping
Email enviado com sucesso!, paras a loja Center Shopping Uberlândia
Email enviado com sucesso!, paras a loja Shopping Recife
Email enviado com sucesso!, paras a loja Shopping Vila Velha
Email enviado com sucesso!, paras a loja Shopping SP Market
Email enviado com sucesso!, paras a loja Shopping Eldorado
Email enviado com sucesso!, paras a loja Shopping Ibirapuera
Email enviado com sucesso!, paras a loja Novo Shopping Ribeirão Preto
Email enviado com sucesso!, paras a loja Iguatemi Campinas
Email enviado com sucesso!, paras a loja Shopping Barra

### Passo 5 - Enviar por e-mail para o gerente

In [9]:
""" import win32com.client as win32

outlook = win32.Dispatch("outlook.application")

nome = emails.loc[emails["Loja"] == loja, "Gerente"].values[0]
mail = outlook.CreateItem(0)
mail.To = emails.loc[emails["loja"] == "E-mail"].values[0]
mail.Subject = f"OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}"
mail.Body = "Texto do E-mail"

attachment = pathlib.Path.cwd() / caminho_backup / loja / f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"
mail.Attachments.Add(str(attachment))

mail.Send()
 """

' import win32com.client as win32\n\noutlook = win32.Dispatch("outlook.application")\n\nnome = emails.loc[emails["Loja"] == loja, "Gerente"].values[0]\nmail = outlook.CreateItem(0)\nmail.To = emails.loc[emails["loja"] == "E-mail"].values[0]\nmail.Subject = f"OnePage Dia {dia_indicador.day}/{dia_indicador.month} - Loja {loja}"\nmail.Body = "Texto do E-mail"\n\nattachment = pathlib.Path.cwd() / caminho_backup / loja / f"{dia_indicador.month}_{dia_indicador.day}_{loja}.xlsx"\nmail.Attachments.Add(str(attachment))\n\nmail.Send()\n '

### Passo 6 - Automatizar todas as lojas

### Passo 7 - Criar ranking para diretoria

In [10]:
faturamento_lojas = vendas.groupby("Loja")[["Loja", "Valor Final"]].sum()
faturamento_lojas_ano = faturamento_lojas.sort_values(by = "Valor Final", ascending = False)
display(faturamento_lojas)


vendas_dia = vendas.loc[vendas["Data"] == dia_indicador, :]
faturamento_lojas_dia = vendas_dia.groupby("Loja")[["Loja", "Valor Final"]].sum()
faturamento_lojas_dia = faturamento_lojas_dia.sort_values(by = "Valor Final", ascending = False)
display(faturamento_lojas_dia)


nome_arquivo = f"{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx"
faturamento_lojas_ano.to_excel(rf"Backup Arquivos Lojas/{nome_arquivo}", index = False)

nome_arquivo = f"{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx"
faturamento_lojas_dia.to_excel(rf"Backup Arquivos Lojas/{nome_arquivo}", index = False)

,Loja,Valor Final
Loja,,
Bourbon Shopping SP,Bourbon Shopping SPBourbon Shopping SPBourbon ...,1726110
Center Shopping Uberlândia,Center Shopping UberlândiaCenter Shopping Uber...,1668921
Iguatemi Campinas,Iguatemi CampinasIguatemi CampinasIguatemi Cam...,1762419
Iguatemi Esplanada,Iguatemi EsplanadaIguatemi EsplanadaIguatemi E...,1699681
Norte Shopping,Norte ShoppingNorte ShoppingNorte ShoppingNort...,1711968
Novo Shopping Ribeirão Preto,Novo Shopping Ribeirão PretoNovo Shopping Ribe...,1678225
Palladium Shopping Curitiba,Palladium Shopping CuritibaPalladium Shopping ...,1721120
Parque Dom Pedro Shopping,Parque Dom Pedro ShoppingParque Dom Pedro Shop...,1631630
Passei das Águas Shopping,Passei das Águas ShoppingPassei das Águas Shop...,1649014
Ribeirão Shopping,Ribeirão ShoppingRibeirão ShoppingRibeirão Sho...,1707122
Rio Mar Recife,Rio Mar RecifeRio Mar RecifeRio Mar RecifeRio ...,1722766
Rio Mar Shopping Fortaleza,Rio Mar Shopping FortalezaRio Mar Shopping For...,1698430
Salvador Shopping,Salvador ShoppingSalvador ShoppingSalvador Sho...,1646739
Shopping Barra,Shopping BarraShopping BarraShopping BarraShop...,1653103
Shopping Center Interlagos,Shopping Center InterlagosShopping Center Inte...,1640486
Shopping Center Leste Aricanduva,Shopping Center Leste AricanduvaShopping Cente...,1682870
Shopping Eldorado,Shopping EldoradoShopping EldoradoShopping Eld...,1648111
Shopping Ibirapuera,Shopping IbirapueraShopping IbirapueraShopping...,1635060
Shopping Iguatemi Fortaleza,Shopping Iguatemi FortalezaShopping Iguatemi F...,1674824
Shopping Midway Mall,Shopping Midway MallShopping Midway MallShoppi...,1590441
Shopping Morumbi,Shopping MorumbiShopping MorumbiShopping Morum...,1586444
Shopping Recife,Shopping RecifeShopping RecifeShopping RecifeS...,1624879
Shopping SP Market,Shopping SP MarketShopping SP MarketShopping S...,1721763
Shopping União de Osasco,Shopping União de OsascoShopping União de Osas...,1663770
Shopping Vila Velha,Shopping Vila VelhaShopping Vila VelhaShopping...,1731167

,Loja,Valor Final
Loja,,
Salvador Shopping,Salvador ShoppingSalvador Shopping,3950
Novo Shopping Ribeirão Preto,Novo Shopping Ribeirão PretoNovo Shopping Ribe...,3400
Center Shopping Uberlândia,Center Shopping UberlândiaCenter Shopping Uber...,2651
Shopping Eldorado,Shopping EldoradoShopping Eldorado,2391
Shopping Center Interlagos,Shopping Center InterlagosShopping Center Inte...,1582
Shopping Recife,Shopping RecifeShopping RecifeShopping Recife,1366
Norte Shopping,Norte ShoppingNorte Shopping,1259
Shopping União de Osasco,Shopping União de OsascoShopping União de Osas...,1207
Shopping Vila Velha,Shopping Vila VelhaShopping Vila VelhaShopping...,937
Bourbon Shopping SP,Bourbon Shopping SP,676
Ribeirão Shopping,Ribeirão ShoppingRibeirão ShoppingRibeirão Sho...,650
Shopping Center Leste Aricanduva,Shopping Center Leste AricanduvaShopping Cente...,485
Palladium Shopping Curitiba,Palladium Shopping CuritibaPalladium Shopping ...,381
Rio Mar Shopping Fortaleza,Rio Mar Shopping Fortaleza,368
Shopping Midway Mall,Shopping Midway Mall,170
Shopping Ibirapuera,Shopping Ibirapuera,118

### Passo 8 - Enviar e-mail para diretoria

In [11]:
def formata_real(valor):
    return f"R$ {valor:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")


load_dotenv() # carega o conteúdo do .env
SENHA_APP = os.getenv("SENHA_APP")

EMAIL_REMETENTE = "ghost60209@gmail.com"

msg = EmailMessage()
msg["From"] = EMAIL_REMETENTE
msg["Cc"] = "ghost60209+copia@gmail.com"
msg["To"] = emails.loc[emails["Loja"] == "Diretoria", "E-mail"].values[0]
msg["Subject"] = f"Ranking Dia {dia_indicador.day}/{dia_indicador.month}"

msg.set_content(f"""
Prezados, bom dia!

Melhor loja do dia em faturamento:
Loja {faturamento_lojas_dia.index[0]}
Faturamento {formata_real(faturamento_lojas_dia.iloc[0]["Valor Final"])}

Pior loja do dia em faturamento:
Loja {faturamento_lojas_dia.index[-1]}
Faturamento {formata_real(faturamento_lojas_dia.iloc[-1]["Valor Final"])}

Melhor loja do ano em faturamento:
Loja {faturamento_lojas_ano.index[0]}
Faturamento {formata_real(faturamento_lojas_ano.iloc[0]["Valor Final"])}

Pior loja do ano em faturamento:
Loja {faturamento_lojas_ano.index[-1]}
Faturamento {formata_real(faturamento_lojas_ano.iloc[-1]["Valor Final"])}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Qualquer dúvida estou à disposição.

Atenciosamente,
Equipe de Dados
""")




# Anexo

caminho_arquivo_1 = pathlib.Path.cwd() / caminho_backup / f"{dia_indicador.month}_{dia_indicador.day}_Ranking Anual.xlsx"
caminho_arquivo_2 = pathlib.Path.cwd() / caminho_backup / f"{dia_indicador.month}_{dia_indicador.day}_Ranking Dia.xlsx"

for caminho in [caminho_arquivo_1, caminho_arquivo_2]:
    msg.add_attachment(
        caminho.read_bytes(),
        maintype = "application",
        subtype = "octet-stream",
        filename = caminho.name
    )

# Enviar e-mail

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp: # aqui abre conexão segura
    smtp.login(EMAIL_REMETENTE, SENHA_APP) # loga na minha conta
    smtp.send_message(msg) # manda a msg


print(f"Email enviado para a Diretoria")

Email enviado para a Diretoria